#!/usr/bin/bash

# This is your Application ID, avoid conflict
appID="net.minecraft.portable"

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName="Minecraft"

# This is the state directory of your application, which is located under "XDG_DATA_HOME"
stateDirectory="mcLaunch_Data"

# This is the target executable to launch
#launchTarget="gtk3-demo"

# Takes boolean value. When enabled, do not process XAuth files and enable X access. Generally this should be always false.
waylandOnly="false"

bindInputDevices="true"

gameMode="true"

# Below you can set envs that will be imported into the application sandbox

bwBindPar="${HOME}/.local/share/PrismLauncher"

__GL_THREADED_OPTIMIZATIONS=0
