#
# tuned configuration
#

[main]
summary=Balanced profile for moeOS

[cpu]
governor=schedutil|powersave
energy_perf_bias=balance-power|power|normal
energy_performance_preference=190|balance-power|power
boost=1
max_perf_pct=95

[service]
#service.moeOS-scheduler@powersave=start
service.moeOS-intel-lpmd=stop

[acpi]
platform_profile=balanced|low-power

[audio]
timeout=5

[video]
radeon_powersave=dpm-battery, auto
panel_power_savings=3

[sysctl]
kernel.sched_energy_aware=0