#!/usr/bin/bash

# This is your Application ID, avoid conflict
appID="org.chromium"

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName="Chromium"

# This is the state directory of your application, which is located under "XDG_DATA_HOME"
stateDirectory="Chromium_Data"

# This is the target executable to launch
launchTarget="/usr/lib/chromium/chromium --ozone-platform-hint=auto --enable-vulkan --enable-zero-copy --enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,WebRTCPipeWireCapturer,TouchpadOverscrollHistoryNavigation --wayland-text-input-version=3 --enable-wayland-ime --no-suid-sandbox"

# Takes boolean value. When enabled, do not process XAuth files and enable X access. Generally this should be always false.
waylandOnly="true"

bindInputDevices="false"

gameMode="false"

# Below you can set envs that will be imported into the application sandbox

bwBindPar=/tmp