#!/bin/bash

function plasma() {
	gsettings set org.gnome.desktop.interface gtk-theme Breeze
	if [[ $(gsettings get org.gnome.desktop.interface color-scheme) =~ default ]]; then
		gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
		scheme="prefer-light"
	fi
	if [[ ${scheme} =~ prefer-dark ]]; then
		gsettings set org.gnome.desktop.interface icon-theme Tela-circle-pink-dark
	elif [[ ${scheme} =~ prefer-light ]]; then
		gsettings set org.gnome.desktop.interface icon-theme Tela-circle-pink-light
	fi
}

function lightMode() {
	scheme=$(gsettings get org.gnome.desktop.interface color-scheme)
	if [[ ${scheme} =~ default ]]; then
		gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
		sleep 0.5s
		scheme=$(gsettings get org.gnome.desktop.interface color-scheme)
	fi
	if [[ ${scheme} =~ prefer-dark ]]; then
		kvantummanager --set moeOS-Dark
		gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark
		gsettings set org.gnome.desktop.interface icon-theme Tela-circle-pink-dark
	elif [[ ${scheme} =~ prefer-light ]]; then
		kvantummanager --set moeOS
		echo "[Info] Tweaking GSettings"
		gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3
		gsettings set org.gnome.desktop.interface icon-theme Tela-circle-pink-light
	fi
}

sleep 5s

scheme=$(gsettings get org.gnome.desktop.interface color-scheme)

while [[ ${scheme} = $(gsettings get org.gnome.desktop.interface color-scheme) ]]; do
	sleep 10s
done

if [[ ${XDG_CURRENT_DESKTOP} = KDE ]]; then
	echo "[Info] Detected DE as KDE"
	plasma
else
	lightMode
fi
