#!/bin/bash

function plasma() {
	gsettings set org.gnome.desktop.interface gtk-theme Breeze
	if [[ ${scheme} =~ prefer-dark ]]; then
		gsettings set org.gnome.desktop.interface icon-theme Tela-circle-pink-dark
	elif [[ ${scheme} =~ prefer-light ]]; then
		gsettings set org.gnome.desktop.interface icon-theme Tela-circle-pink-light
	fi
}

function lightMode() {
	scheme=$(gsettings get org.gnome.desktop.interface color-scheme)
	if [[ ${scheme} =~ prefer-dark ]]; then
		kvantummanager --set moeOS-Dark
		gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark
		gsettings set org.gnome.desktop.interface icon-theme Tela-circle-pink-dark
	elif [[ ${scheme} =~ prefer-light ]]; then
		kvantummanager --set moeOS
		echo "[Info] Tweaking GSettings"
		gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3
		gsettings set org.gnome.desktop.interface icon-theme Tela-circle-pink-light
	fi
}

function loop() {
	gsettings monitor org.gnome.desktop.interface color-scheme | while read -r line; do
		echo "Triggered theme change"
		if [[ ${scheme} =~ default ]]; then
			gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
			sleep 0.5s
			scheme=$(gsettings get org.gnome.desktop.interface color-scheme)
		fi
		main
	done
}

function main() {
	if [[ ${XDG_CURRENT_DESKTOP} = KDE ]]; then
		echo "[Info] Detected DE as KDE"
		plasma
	else
		lightMode
	fi
}

main
loop