#!/bin/bash

function main() {
	cd $(dirname "$@")
	baseName=$(basename "$@")
	if [[ ${baseName} =~ ".jpg" ]]; then
		conName="$(echo ${baseName} | sed 's|.jpg|.webp|g')"
	elif [[ ${baseName} =~ ".png" ]]; then
		conName="$(echo ${baseName} | sed 's|.png|.webp|g')"
	elif [[ ${baseName} =~ ".jpeg" ]]; then
		conName="$(echo ${baseName} | sed 's|.jpeg|.webp|g')"
	else
		conName="${baseName}.avif"
	fi
	magick convert "${baseName}" "${conName}"
	rm "${baseName}"
	killall wl-copy
	wl-copy -o < "${conName}"
}

main "$@"