#!/bin/bash
bwrap \
	--symlink usr/lib /lib \
	--symlink usr/lib64 /lib64 \
	--symlink usr/bin /bin \
	--symlink usr/bin /sbin \
	--ro-bind /usr /usr \
	--ro-bind /etc /etc \
	--dev /dev \
	--dev-bind /dev/dri /dev/dri \
	--dev-bind /dev/shm /dev/shm \
	--bind /proc /proc \
	--ro-bind /sys/dev/char /sys/dev/char \
	--ro-bind /sys/devices /sys/devices \
	--bind /run /run \
	--tmpfs /tmp \
	--bind "$HOME" "$HOME" \
	--setenv GTK_IM_MODULE ibus \
	/usr/bin/chromium \
		--ozone-platform=wayland \
		--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,WebRTCPipeWireCapturer,TouchpadOverscrollHistoryNavigation \
		--enable-wayland-ime
		$@
