#!/bin/bash
bwrap \
	--symlink usr/lib /lib \
	--symlink usr/lib64 /lib64 \
	--symlink usr/bin /bin \
	--symlink usr/bin /sbin \
	--ro-bind /usr /usr \
	--ro-bind /etc /etc \
	--dev /dev \
	--dev-bind /dev/dri /dev/dri \
	--dev-bind /dev/shm /dev/shm \
	--bind /proc /proc \
	--ro-bind /sys/dev/char /sys/dev/char \
	--ro-bind /sys/devices /sys/devices \
	--bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
	--chmod 0700 "$XDG_RUNTIME_DIR" \
	--tmpfs /tmp \
	--bind "$HOME" "$HOME" \
	env GTK_IM_MODULE=ibus \
		/usr/bin/chromium \
			--gtk-version=4 \
			--ozone-platform-hint=auto \
			--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder \
			"$@"
