#!/bin/bash
bwrap \
	--symlink usr/lib /lib \
	--symlink usr/lib64 /lib64 \
	--symlink usr/bin /bin \
	--symlink usr/bin /sbin \
	--ro-bind /usr /usr \
	--ro-bind /etc /etc \
	--dev /dev \
	--dev-bind /dev/dri /dev/dri \
	--dev-bind /dev/shm /dev/shm \
	--bind /proc /proc \
	--ro-bind /sys/dev/char /sys/dev/char \
	--ro-bind /sys/devices /sys/devices \
	--bind "$XDG_RUNTIME_DIR" "$XDG_RUNTIME_DIR" \
	--bind /run /run \
	--chmod 0700 "$XDG_RUNTIME_DIR" \
	--bind /tmp /tmp \
	--bind /var /var \
	--bind "$HOME" "$HOME" \
	/usr/bin/chromium \
		--ozone-platform-hint=auto \
		--enable-wayland-ime \
		--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder \
		"$@"
