#!/usr/bin/bash

# Unfinished, proof of concept

exit 0

# First query the utils version
utilsVer=$(pacman -Q nvidia-utils | cut -d' ' -f2 | cut -d'-' -f1)
export _arch="x86_64"
extensionDir="/var/lib/flatpak/extension/org.freedesktop.Platform.GL.host/${_arch}/1.4"

function grepFiles() {
	pacman -Ql nvidia-utils | cut -d' ' -f2
}

function prepare() {
	if [[ ! ${extensionDir} ]]; then
		exit 1
	fi
	if [ ! -d "${extensionDir}" ]; then
		mkdir "${extensionDir}" -p
	else
		rm -r "${extensionDir}"/*
	fi
	install -d "${extensionDir}"/lib
}

function copyFiles() {
	# Process library first
	for file in $(pacman -Ql nvidia-utils | cut -d' ' -f2 | grep '/usr/lib/lib'); do
		cp -a "${file}" "${extensionDir}/lib"
	done
	cp -a /usr/lib/gbm "${extensionDir}/lib"
	cp -a /usr/lib/nvidia "${extensionDir}/lib"
	cp -a /usr/lib/vdpau "${extensionDir}/lib"
	install -d "${extensionDir}/lib"/xorg/modules/drivers
	cp -a /usr/lib/xorg/modules/drivers/nvidia_drv.so \
		"${extensionDir}/lib"/xorg/modules/drivers
	install -d "${extensionDir}"/vulkan/icd.d
	cp -a /usr/share/vulkan/icd.d/nvidia_icd.json \
		"${extensionDir}"/vulkan/icd.d
	install -d "${extensionDir}"/glvnd/egl_vendor.d
	cp -a /usr/share/glvnd/egl_vendor.d/10_nvidia.json \
		"${extensionDir}"/glvnd/egl_vendor.d/
}

function main() {
	prepare
	copyFiles
}

main