#!/usr/bin/bash

function nvProp() {
	if [[ ! -e /dev/nvidia0 ]] && [[ ! -e /dev/nvidia1 ]]; then
		echo "NVIDIA proprietary device not present!"
		return 1
	fi
	if [[ $(find /dev/dri/renderD* -maxdepth 0 -type c 2>/dev/null | wc -l) -eq 1 && -e /dev/nvidia0 ]]; then
		echo "Using single GPU, bailing out..."
		exit 0
	else
		echo "Detecting multiple GPUs... Taking measures"
		envAdd 'VK_LOADER_DRIVERS_DISABLE=nvidia_icd.json'
	fi
}

function envAdd() {
	echo "$@" >>"$(pwd)/env"
}

function expose() {
	count=$(cat "$(pwd)/env" | wc -l)
	for line in {1..${count}}; do
		local env=$(cat "$(pwd)/env" | head -n "${line}")
		echo "Exposing ${env}"
		systemctl set-environment ${env}
	done
}

function envInt() {
	if [[ -f "$(pwd)/env" ]]; then
		rm "$(pwd)/env"
	fi
	touch "$(pwd)/env"
}

function main() {
	set -m
	envInt
	nvProp
	envAdd "DRI_PRIME=0"
}

$@