#!/bin/bash
function download(){
	info "Downloading subscribe file..."
	execute curl "${url}" -o /var/tmp/config.yaml
}

function execute(){
	"$@"
	if [[ $? = 0 ]]; then
		return 0
	else	
		err=$?
		info "Something went wrong, error code ${err}"
		exit ${err}
	fi
}

function addMissingTun(){
	info "Enabling TUN..."
	echo '''tun:
  enable: true
  stack: gvisor
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true''' >>/var/tmp/config.yaml
  echo "Done."
}

function enableTunInplace(){
	info 'Updating the yaml file...'
	execute yq -i '.tun.enable = "true"' /var/tmp/config.yaml
	echo done.
}

function info(){
	echo "  ==> [Info]: $@"
}

function mergeConfig(){
	if [[ $(cat /var/tmp/merge.yaml) ]]; then
		info 'Merging configuration...'
		yq ea '. as $item ireduce ({}; . * $item )' /var/tmp/{config.yaml,merge.yaml} >/var/tmp/config.yaml.new
		mv /var/tmp/config.yaml.new /var/tmp/config.yaml
	else
		info 'Skipping merge'
	fi

}

function main(){
	rm /var/tmp/* -r
	flags="$@"
	download
	if [[ $(yq '.tun.enable' /var/tmp/config.yaml) = null ]]; then
		addMissingTun
		info "Config check completed."
	elif [[ $(yq '.tun.enable' /var/tmp/config.yaml) = 'false' ]]; then
		info "TUN is disabled"
		enableTunInplace
		info "Config check completed."
	else
		info "Config check completed."
	fi
	if [[ ${flags} =~ redir-host ]]; then
		info 'Setting enhanced mode to redir-host...'
		yq -i '.dns.enhanced-mode = "redir-host"' /var/tmp/config.yaml
	fi
	if [[ ${flags} =~ fake-ip ]]; then
		info 'Setting enhanced mode to fake-ip...'
		yq -i '.dns.enhanced-mode = "fake-ip"' /var/tmp/config.yaml
	fi
	if [[ ${flags} =~ load-balance ]]; then
		info "Enabling load balancing mode..."
		sed -i "s/url-test/load-balance/" /var/tmp/config.yaml
	fi
	mergeConfig
}

main "$@"
