#!/bin/bash

function gnomeTheme() {
	echo "Installing Firefox theme..."
	for profile in $(ls "${HOME}/.mozilla/firefox" | grep -v '.ini'); do
		if [ ! -f ${HOME}/.mozilla/firefox/${profile}/chrome/firefox-gnome-theme ]; then
			echo "Working on ${profile}"
			cd "${HOME}/.mozilla/firefox/${profile}"
			if [[ $? = 0 ]]; then
				mkdir chrome
				cd chrome
				ln -s /usr/lib/firefox-gnome-theme firefox-gnome-theme
				[[ -s userChrome.css ]] || echo >> userChrome.css
				[[ -s userContent.css ]] || echo >> userContent.css
				sed -i '1s/^/@import "firefox-gnome-theme\/userChrome.css";\n/' userChrome.css
				sed -i '1s/^/@import "firefox-gnome-theme\/userContent.css";\n/' userContent.css
				cd ..
				ln -fs chrome/firefox-gnome-theme/configuration/user.js user.js
			fi
		else
			echo "Profile ${profile} skipped"
		fi
	done
}

function deleteGnomeTheme() {
	if [ ! -d "${HOME}/.mozilla/firefox" ]; then
		return 0
	fi
	rm "${HOME}"/.mozilla/firefox/*/chrome -r
	rm "${HOME}"/.mozilla/firefox/*/user.js
}

function main() {
	pathNow="$(pwd)"
	gnomeTheme
	#deleteGnomeTheme
	cd "${pathNow}"
}

main
