#!/bin/bash

if [ ! -f /usr/bin/thunderbird ]; then
	exit 0
fi
if [ $(cat /usr/share/applications/org.mozilla.Thunderbird.desktop) =~ 'thunderbird-bwrap' ]; then
	exit 0
else
	sed -i \
		"s|Exec=thunderbird|Exec=thunderbird-bwrap|g" \
		/usr/share/applications/org.mozilla.Thunderbird.desktop
fi