#!/bin/bash

function _notify() {
	notify-send -i moeos -u normal -t 5 "moeOS Setup" "$1"
	sleep 2
}

function main() {
	if [ ! "${XDG_CONFIG_HOME}" ]; then
		export XDG_CONFIG_HOME="${HOME}/.config"
	fi
	echo "[Info] Starting moeOS Autoconf"
	setupFont
	setupBreeze
	mkdir -p \
		"${XDG_CONFIG_HOME}/Phonon"
	ln -sr \
		/etc/mpv/mpv.conf \
		"${XDG_CONFIG_HOME}/Phonon/mpv.conf"
	checkExist
	_notify "Setting up moeOS"
	moeOS-setup-firefox
	checkExist set
}

function setupFont() {
	echo "[Info] Setting up fonts"
	mkdir -p ~/.config/fontconfig
	cp /etc/fonts/conf.d/99-moeos.conf ~/.config/fontconfig/fonts.conf
}

function moeOS-setup-firefox() {
	if [[ ${moePreferDE} = KDE ]]; then
		if [ ! -d "${HOME}/.mozilla/firefox" ]; then
			return 0
		fi
		rm "${HOME}"/.mozilla/firefox/*/chrome -r
		rm "${HOME}"/.mozilla/firefox/*/user.js
		return 0
	fi
	echo "[Info] Setting up Firefox"
	bash "/usr/lib/moeOS/moeOS-setup-firefox" 1>/dev/null 2>/dev/null
}

function setupBreeze() {
	if [[ ${XDG_CURRENT_DESKTOP} = KDE ]]; then
	# I fucking hate Flatpak prohibiting the exposure of /etc/xdg
		for file in Trolltech.conf kdeglobals breezerc; do
			if [ ! -f ${XDG_CONFIG_HOME}/${file} ]; then
				cp /etc/xdg/${file} ${XDG_CONFIG_HOME}
			fi
		done
	else
		cp -r /etc/gtk-{4,3}.0 "${XDG_CONFIG_HOME}/"
	fi
}

function checkExist() {
	if [ "${_moeOS_Setup}" = 1 ]; then
		echo "_moeOS_Setup detected!"
	elif [ -f "${XDG_CONFIG_HOME}/moeOS/state" ]; then
		setupFont
		exit 0
	fi
	if [[ "$@" =~ set ]]; then
		mkdir -p "${XDG_CONFIG_HOME}/moeOS"
		touch "${XDG_CONFIG_HOME}/moeOS/state"
		_notify "moeOS has been set up"
	fi
}

main
