#!/bin/bash
function download(){
	info "Downloading subscribe file..."
	execute curl "${url}" -o /var/tmp/config.yaml
}

function execute(){
	"$@"
	if [[ $? = 0 ]]; then
		return 0
	else	
		err=$?
		info "Something went wrong, error code ${err}"
		exit ${err}
	fi
}

function enableTunInplace(){
	info 'Updating the yaml file...'
	execute yq -i '.tun.enable = true' /var/tmp/config.yaml
	echo done.
}

function info(){
	echo "  ==> [Info]: $@"
}

function mergeConfig(){
	if [[ -f /etc/moeOS-clash-meta/merge.yaml ]] && [[ $(/etc/moeOS-clash-meta/merge.yaml) =~ ' ' ]]; then
		info 'Merging configuration...'
		yq ea '. as $item ireduce ({}; . * $item )' /var/tmp/config.yaml /etc/moeOS-clash-meta/merge.yaml >/var/tmp/config.yaml.new
		mv /var/tmp/config.yaml.new /var/tmp/config.yaml
	else
		info 'Skipping merge'
	fi

}

function main(){
	cp /usr/share/v2ray/geosite.dat /var/tmp/geosite.dat
	cp /etc/clash/Country.mmdb /var/tmp
	flags="$@"
	download
	#if [[ $(yq '.tun.enable' /var/tmp/config.yaml) = 'false' ]] && [[ ${flags} =~ no-tproxy ]]; then
	#	info "TUN is disabled"
	#	enableTunInplace
	#	info "Config check completed."
	#else
	#	info "Using tproxy..."
	#	execute yq -i '.tun.enable = false' /var/tmp/config.yaml
	#	execute yq -i '.tproxy-port = 65529' /var/tmp/config.yaml
	#	info "Config check completed."
	#fi
	#if [[ ${flags} =~ load-balance ]]; then
	#	info "Enabling load balancing mode..."
	#	sed -i "s/url-test/load-balance/" /var/tmp/config.yaml
	#fi
	#mergeConfig
	#echo "[Info] Config has been modified"
	#enableTunInplace
}

#bash /usr/lib/moeOS/seconnect &
main "$@"
