#!/bin/bash

function main() {
	if [ ! -f /var/lib/flatpak/overrides ]; then
		mkdir -p /var/lib/flatpak/
		touch /var/lib/flatpak/overrides
	fi
	replace "/usr/share/moeOS-Docs/os-release" "/etc/os-release"
	replace "/usr/share/moeOS-Docs/os-release" "/usr/lib/os-release"
	replace "/usr/share/moeOS-Docs/nsswitch.conf" "/etc/nsswitch.conf"
	replace "/usr/share/moeOS-Docs/makepkg.conf" "/etc/makepkg.conf"
	replace "/usr/share/moeOS-Docs/flatpak.overrides" "/var/lib/flatpak/overrides/global"
	replace "/usr/share/moeOS-Docs/ibus-rime.conf.d/default.yaml" "/usr/share/rime-data/default.yaml"
	for unit in nvidia-powerd nvidia-suspend nvidia-resume nvidia-persistenced; do
		if [[ -f /usr/lib/systemd/system/"${unit}".service ]]; then
			systemctl enable ${unit}
		fi
	done
	systemctl enable --now chronyd moeOS-nvboost systemd-resolved ipp-usb watchdog avahi-daemon cups cups-browsed power-profiles-daemon bluetooth NetworkManager systemd-oomd thermald
	#systemctl mask systemd-timesyncd # Do we really need risk masking it?
	systemctl --global enable snotify moeOS-setup moeOS-autoColor
	ln -sfr /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
	plymouth-set-default-theme moe-next
	/usr/lib/moeOS/patch-chromium
	/usr/lib/moeOS/patch-steam
	flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
	flatpak remote-modify flathub --url=https://mirror.sjtu.edu.cn/flathub
	#flatpak remote-modify flathub --url=https://dl.flathub.org/repo/
	# Flatpak thingy
	flatpak mask --remove org.freedesktop.Platform.GL.nvidia 2>/dev/null
	flatpak mask --remove 'org.freedesktop.Platform.GL.nvidia*' 2>/dev/null
	flatpak mask --remove 'org.freedesktop.Platform.GL32.nvidia*' 2>/dev/null

	if [[ $(cat /etc/security/faillock.conf | grep "fail_interval =") = "# fail_interval = 900" ]]; then
		sed -i "s|# fail_interval = 900|fail_interval = 30|g" /etc/security/faillock.conf
	fi
	if [[ $(cat /etc/security/faillock.conf | grep "deny =") = "# deny = 3" ]]; then
		sed -i "s|# deny = 3|deny = 5|g" /etc/security/faillock.conf
	fi
	flatpak remove --unused --noninteractive
}

function replace() {
	if [[ $(diff $1 $2) ]]; then
		cp $1 $2
	fi
}

main "$@"
