#!/bin/bash

function main() {
	if [ ! -f /var/lib/flatpak/overrides/global ]; then
		mkdir -p /var/lib/flatpak/overrides
		touch /var/lib/flatpak/overrides/global
	fi
	replace "/usr/share/moeOS-Docs/os-release" "/etc/os-release"
	replace "/etc/fstab.moe" "/etc/fstab"
	replace "/usr/share/moeOS-Docs/os-release" "/usr/lib/os-release"
	replace "/usr/share/moeOS-Docs/makepkg.conf" "/etc/makepkg.conf"
	replace "/usr/share/moeOS-Docs/flatpak.overrides" "/var/lib/flatpak/overrides/global"
	replace "/usr/share/moeOS-Docs/ibus-rime.conf.d/default.yaml" "/usr/share/rime-data/default.yaml"
	replace "/usr/share/moeOS-Docs/avahi-daemon.conf" "/etc/avahi/avahi-daemon.conf"
	replace "/usr/share/moeOS-Docs/bluez/main.conf" "/etc/bluetooth/main.conf"
	replace "/usr/share/moeOS-Docs/wireless-regdom" "/etc/conf.d/wireless-regdom"
	replace "/usr/share/moeOS-Docs/libreoffice/sofficerc" "/etc/libreoffice/sofficerc"
	replace \
		"/usr/share/moeOS-Docs/mkinitcpio.d/linux-zen.preset" \
		"/etc/mkinitcpio.d/linux-zen.preset"
	replace \
		"/usr/share/moeOS-Docs/mkinitcpio.conf" \
		"/etc/mkinitcpio.conf"

	if [[ $(cat /etc/nsswitch.conf | grep 'hosts:') =~ mdns ]]; then
		replace "/usr/share/moeOS-Docs/nsswitch-bak.conf" "/etc/nsswitch.conf"
	fi

	if [ ! -f /var/lib/sbctl/keys/db/db.key ]; then
		echo "Generating secure boot credentials..."
		sbctl create-keys
	fi
	if [ ! -f /var/lib/moeOS/TPM-Keys/Private.pem ]; then
		rm -rf /var/lib/moeOS/TPM-Keys
		mkdir -p \
			--mode=700 \
			/var/lib/moeOS/TPM-Keys
		ukify \
			genkey \
			--pcr-public-key=/var/lib/moeOS/TPM-Keys/Public.pem \
			--pcr-private-key=/var/lib/moeOS/TPM-Keys/Private.pem
	fi

	systemctl disable \
		moeOS-scheduler@autopilot \
		moeOS-scheduler &

	systemctl unmask \
		systemd-resolved \
		moeOS-scheduler.service \
		moeOS-cgtproxy \
		moeOS-cgproxy \
		nvidia-powerd \
		nvidia-suspend \
		nvidia-resume \
		nvidia-suspend-then-hibernate \
		nvidia-hibernate &

	systemctl enable \
		systemd-resolved \
		rtkit-daemon \
		NetworkManager-wait-online \
		moeOS-nvboost \
		chronyd \
		ipp-usb \
		avahi-daemon \
		cups \
		cups-browsed \
		tuned \
		tuned-ppd \
		bluetooth \
		NetworkManager \
		ModemManager \
		systemd-oomd \
		moeOS-fstrim.timer --now

	systemctl enable \
		moeOS-startup-chime.service \
		nvidia-powerd \
		nvidia-suspend \
		nvidia-resume \
		nvidia-hibernate \
		nvidia-resume \
		nvidia-suspend-then-hibernate \
		snapper-timeline.timer \
		snapper-cleanup.timer

	systemctl mask \
		systemd-timesyncd \
		pkgstats \
		passim \
		dhcpcd \
		nvidia-persistenced \
		scx.service \
		scx_loader.service \
		fstrim.timer &
	systemctl --global \
		enable \
		snotify moeOS-setup moeOS-autoColor
	ln -sfr \
		/run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
	plymouth-set-default-theme moe-next
	/usr/lib/moeOS/patch-chromium 2>/dev/null &
	flatpak remote-add \
		--if-not-exists \
		flathub https://dl.flathub.org/repo/flathub.flatpakrepo
	#flatpak remote-modify \
	#	flathub \
	#	--url=https://mirror.sjtu.edu.cn/flathub &
	#flatpak remote-modify flathub --url=https://dl.flathub.org/repo/
	flatpak remote-modify flathub --url=https://mirrors.ustc.edu.cn/flathub
	# Flatpak thingy
	flatpak mask --remove org.freedesktop.Platform.GL.nvidia 2>/dev/null &
	flatpak mask --remove 'org.freedesktop.Platform.GL.nvidia*' 2>/dev/null &
	flatpak mask --remove 'org.freedesktop.Platform.GL32.nvidia*' 2>/dev/null &

	if [[ $(cat /etc/security/faillock.conf | grep "fail_interval =") = "# fail_interval = 900" ]]; then
		sed -i "s|# fail_interval = 900|fail_interval = 30|g" /etc/security/faillock.conf
	fi
	if [[ $(cat /etc/security/faillock.conf | grep "deny =") = "# deny = 3" ]]; then
		sed -i "s|# deny = 3|deny = 5|g" /etc/security/faillock.conf
	fi
	flatpak remove --unused --noninteractive &
	systemctl mask \
		--global \
		app-org.kde.discover.notifier@autostart.service 2>/dev/null &
	systemctl unmask \
		--global \
		app-org.gnome.Software@autostart.service &
	btrfs subvolume create /.snapshots
	btrfs subvolume create /home/.snapshots
}

function replace() {
	install -vDm755 "$1" "$2"
}

set -m
main "$@"
