#!/bin/bash

if [ ! -f /proc/driver/nvidia/suspend ]; then
    exit 0
fi

case "$1" in
    is-suspend-then-hibernate-supported)
	exit 0
        ;;
    suspend|hibernate)
        echo "$1" > /proc/driver/nvidia/suspend
        RET_VAL=$?
        exit $RET_VAL
        ;;
    resume)
        echo "$1" > /proc/driver/nvidia/suspend
        exit 0
        ;;
    *)
        exit 1
esac