#!/bin/bash

if [[ ! -f /usr/bin/loupe ]]; then
	exit 0
fi
if [[ $(cat /usr/share/applications/org.gnome.Loupe.desktop) =~ 'loupe-wrapper' ]]; then
	exit 0
else
	sed -i \
		"s|Exec=loupe|Exec=loupe-wrapper|g" \
		/usr/share/applications/org.gnome.Loupe.desktop
fi