#!/bin/bash

function replace() {
	if [[ $(cat "$@") =~ "steam-sandboxed" ]]; then
		return 0
	else
		sed -i 's|Exec=steam|Exec=sandboxed|g' "$@"
	fi
}

if [ ! -f /usr/share/applications/steam.desktop ]; then
	exit 0
fi

replace /usr/share/applications/steam.desktop
if [ -f /usr/share/applications/steam-native.desktop ]; then
	ln -sf /dev/null /usr/share/applications/steam-native.desktop
fi
