#!/usr/bin/bash

function checkInst() {
	if [[ "$(flatpak list)" =~ com.valvesoftware.Steam ]]; then
		return 0
	else
		flatpak install --assumeyes --or-update flathub com.valvesoftware.Steam
	fi
}

function gbmProbe() {
	if [ -f /etc/environment.d/moeOS-nvidia*.conf ]; then
		nvidiaVer="$(pacman -Q nvidia-utils | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+)-([0-9]+)/\1/' | sed 's/\./-/g')"
		backendPath="/usr/lib/x86_64-linux-gnu/GL/nvidia-"${nvidiaVer}"/extra/gbm"
	fi
}

function main() {
	env -u ENABLE_HDR_WSI \
	env \
		DXVK_HDR=1 \
		STEAM_GAMESCOPE_HDR_SUPPORTED=1 \
		ENABLE_GAMESCOPE_WSI=1 \
		gamescope \
		--hdr-itm-enable \
		--hdr-itm-target-nits=1200 \
		--hdr-itm-sdr-nits=40 \
		-W 1680 -H 1050 \
		--disable-color-management \
		--hdr-enabled \
		-e \
		-F fsr \
		-- \
			env \
			GBM_BACKENDS_PATH="${backendPath}" \
			ENABLE_GAMESCOPE_WSI=1 \
			flatpak run com.valvesoftware.Steam \
			-gamepadui -steamos3 -steampal -pipewire-dmabuf $@
}

checkInst
gbmProbe
main $@
