#!/usr/bin/bash

function checkInst() {
	if [[ "$(flatpak list)" =~ com.valvesoftware.Steam ]]; then
		return 0
	else
		flatpak install --assumeyes --or-update flathub com.valvesoftware.Steam
	fi
}

function gbmProbe() {
	if [ -f /etc/environment.d/moeOS-nvidia*.conf ]; then
		nvidiaVer="$(pacman -Q nvidia-utils | sed -E 's/.* ([0-9]+\.[0-9]+\.[0-9]+)-([0-9]+)/\1/' | sed 's/\./-/g')"
		backendPath="/usr/lib/x86_64-linux-gnu/GL/nvidia-"${nvidiaVer}"/extra/gbm"
	fi
}

function main() {
	gamescope \
		--adaptive-sync \
		-W 1680 -H 1050 \
		--hdr-enabled \
		--expose-wayland \
		-e \
		-- \
			env \
			GBM_BACKENDS_PATH="${backendPath}" \
			flatpak run com.valvesoftware.Steam $@
}

checkInst
gbmProbe
main $@