#!/usr/bin/bash

echo 10 > /sys/fs/cgroup/system.slice/cpu.uclamp.max
echo 1 > /sys/fs/cgroup/system.slice/io.weight
echo 20 > /sys/fs/cgroup/system.slice/cpu.weight

echo 10000 > /sys/fs/cgroup/user.slice/cpu.weight
echo 10000 > /sys/fs/cgroup/user.slice/io.weight
echo 100 > /sys/fs/cgroup/user.slice/cpu.uclamp.min