#!/usr/bin/bash

if [[ "$1" =~ post ]]; then
	systemctl restart \
	NetworkManager-wait-online.service \
	moeOS-proxy \
	moeOS-seconnect
else
	systemctl stop \
	NetworkManager-wait-online.service \
	moeOS-proxy
fi