[qt]
enable = true
[qt.theme]
light = "kvantum"
dark = "kvantum-dark"

[icon]
enable = true
[icon.theme]
light = "Adwaita"
dark = "Adwaita"

[gtk]
enable = true
[gtk.theme]
light = "Adw"
dark = "Adw-dark"